#pragma once

#include "source2sdk/source2gen/source2gen.hpp"
#include <cstddef>
#include <cstdint>
#include "source2sdk/client/C_PointEntity.hpp"

// /////////////////////////////////////////////////////////////
// Module: client
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk
{
    namespace client
    {
        // Registered alignment: 0x8
        // Alignment: 0x8
        // Standard-layout class: false
        // Size: 0x628
        // Has VTable
        #pragma pack(push, 1)
        class CMapInfo : public source2sdk::client::C_PointEntity
        {
        public:
            std::int32_t m_iBuyingStatus; // 0x5f8            
            float m_flBombRadius; // 0x5fc            
            std::int32_t m_iPetPopulation; // 0x600            
            bool m_bUseNormalSpawnsForDM; // 0x604            
            bool m_bDisableAutoGeneratedDMSpawns; // 0x605            
            uint8_t _pad0606[0x2]; // 0x606
            float m_flBotMaxVisionDistance; // 0x608            
            std::int32_t m_iHostageCount; // 0x60c            
            bool m_bFadePlayerVisibilityFarZ; // 0x610            
            bool m_bRainTraceToSkyEnabled; // 0x611            
            uint8_t _pad0612[0x2]; // 0x612
            float m_flEnvRainStrength; // 0x614            
            float m_flEnvPuddleRippleStrength; // 0x618            
            float m_flEnvPuddleRippleDirection; // 0x61c            
            float m_flEnvWetnessCoverage; // 0x620            
            float m_flEnvWetnessDryingAmount; // 0x624            
            
            // Datamap fields:
            // int32_t InputFireWinCondition; // 0x0
        };
        #pragma pack(pop)
        
        // Cannot assert offsets of fields in CMapInfo because it is not a standard-layout class
        
        static_assert(sizeof(source2sdk::client::CMapInfo) == 0x628);
    };
};
