#pragma once

#include "source2sdk/source2gen/source2gen.hpp"
#include <cstddef>
#include <cstdint>
#include "source2sdk/server/CPointEntity.hpp"

// /////////////////////////////////////////////////////////////
// Module: server
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk
{
    namespace server
    {
        // Registered alignment: 0x8
        // Alignment: 0x8
        // Standard-layout class: false
        // Size: 0x520
        // Has VTable
        #pragma pack(push, 1)
        class CMapInfo : public source2sdk::server::CPointEntity
        {
        public:
            std::int32_t m_iBuyingStatus; // 0x4f0            
            float m_flBombRadius; // 0x4f4            
            std::int32_t m_iPetPopulation; // 0x4f8            
            bool m_bUseNormalSpawnsForDM; // 0x4fc            
            bool m_bDisableAutoGeneratedDMSpawns; // 0x4fd            
            uint8_t _pad04fe[0x2]; // 0x4fe
            float m_flBotMaxVisionDistance; // 0x500            
            std::int32_t m_iHostageCount; // 0x504            
            bool m_bFadePlayerVisibilityFarZ; // 0x508            
            bool m_bRainTraceToSkyEnabled; // 0x509            
            uint8_t _pad050a[0x2]; // 0x50a
            float m_flEnvRainStrength; // 0x50c            
            float m_flEnvPuddleRippleStrength; // 0x510            
            float m_flEnvPuddleRippleDirection; // 0x514            
            float m_flEnvWetnessCoverage; // 0x518            
            float m_flEnvWetnessDryingAmount; // 0x51c            
            
            // Datamap fields:
            // int32_t InputFireWinCondition; // 0x0
        };
        #pragma pack(pop)
        
        // Cannot assert offsets of fields in CMapInfo because it is not a standard-layout class
        
        static_assert(sizeof(source2sdk::server::CMapInfo) == 0x520);
    };
};
